config/routes.rb
Rails.application.routes.draw do
  root "questions#index"

  resources :questions do
    resources :comments, only: [:create, :destroy]
    resources :answers, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy]
  end

  resources :answers do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  belongs_to :user

  validates :title, :description, presence: true

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @questions = Question.all.order('created_at DESC')
  end

  def show
    # @Vote_allow enables user to vote once
    if user_signed_in?
      @vote_allow_question = @question.votes.where(user_id: current_user.id).size > 0
      # @question.answers.each do |answer|
      #   @vote_allow_answer = answer.votes.where(user_id: current_user.id).size > 0
      # end
    end
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      @errors = @question.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @question.destroy

    redirect_to questions_path
  end

  def update
    if @question.update(question_params)
      redirect_to questions_path
    else
      @errors = @question.errors.full_messages
      render 'edit'
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :description).merge(user_id: current_user.id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<div class="row">
  <div class="col-sm-8">
    <div class="panel">
      <h1>Edit Question</h1>
      <% if @errors %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @errors.each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <%= form_for(@question) do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: 'form-control', placeholder: 'Write your question here...' %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Write your description here...' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update", class: 'btn btn-custom' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/questions/index.html.erb
<h1>Questions</h1>
<div class="row">
  <div class="col-sm-8">
    <% @questions.each do |q| %>
      <div class='question-preview panel'>
        <div class="author">
          <%= image_tag("default-user.png", :class => "image_author") %>
          <div class="name_author"><%= q.user.name %></div>
        </div>
        <div class="content">
          <h4 class="title"><%= link_to q.title, question_path(q) %></h4>
          <div class="excerpt"><%= truncate(q.description, length: 300) %></div>
          <% if current_user %>
            <% if current_user.id == q.user.id %>
              <div class="menu-questions">
                <ul>
                  <li class="edit"><%= fa_icon "edit" %><%= link_to ' Edit question', edit_question_path(q) %></li>
                  <li class="delete"><%= fa_icon "trash-o" %><%= link_to ' Delete question', question_path(q), method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="data">
          <ul>
            <li><span class="answers_data"><%= q.answers.size %></span> answers</li>
            <li><%= fa_icon "thumbs-o-up" %> <%= q.votes.size %> votes</li>
            <li><%= fa_icon "comment-o" %> <%= q.comments.size %> comments</li>
            <li><%= fa_icon "clock-o" %> <%= q.created_at.pretty %></li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/questions/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="forms-section panel">
      <h1>New Questions</h1>
      <% if @errors %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @errors.each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <%= form_for :question, url: questions_path do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: 'form-control', placeholder: 'Write your question here...' %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Write your description here...' %>
        </div>
        <div class="form-group">
          <%= f.submit "Create", class: 'btn btn-custom' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-sm-8">
    <div class="question-full panel">
      <div class="author">
        <%= image_tag("default-user.png", :class => "image_author") %>
        <div class="name_author"><%= @question.user.name %></div>
      </div>
      <div class="content">
        <h1 class="title"><%= @question.title %></h1>
        <p><%= @question.description %></p>
        <div class="comments_to_question">
          <h4><%= @question.comments.count %> Comments for this question</h4>
          <% @question.comments.each do |c| %>
            <div class="comment">
              <div class="author_name"><%= c.user.name %></div>
              <div class="comment_text"><%= c.description %></div>
            </div>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <a href="#" class="link" id="add_comment">Add a comment</a>
          <div class="form_comment">
            <% if @errors %>
            <div class="alert alert-danger" role="alert">
              <ul>
                <% @errors.each do |error| %>
                <li><%= error %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= form_for [@question, @question.comments.new] do |f| %>
              <div class="form-group">
                <%= f.label 'Comment' %>
                <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Write your comment here...' %>
              </div>
              <div class="form-group">
                <%= f.submit "Add Comment", class: 'btn btn-custom' %>
              </div>
            <% end %>
          </div>
      <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="votes">
          <ul>
            <li>
              <% if @vote_allow_question %>
                <span class="up-vote disabled"><%= fa_icon "thumbs-o-up" %></span>
              <% else %>
                <%= form_for [@question, @question.votes.new] do |f| %>
                  <%= f.button fa_icon "thumbs-o-up", class: 'up-vote' %>
                <% end %>
              <% end %>
            </li>
            <li><span class="votes-total"><%= @question.votes.count %></span></li>
            <li>
            <% unless @vote_allow_question %>
              <span class="down-vote disabled"><%= fa_icon "thumbs-o-down" %></span>
            <% else %>
              <%= link_to question_vote_path(@question), method: :delete do %>
                <%= fa_icon "thumbs-o-down", class: 'down-vote' %>
              <% end %>
            <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="answers_to_question">
      <h3><%= @question.answers.count %> Answers</h3>
      <% @question.answers.each do |a| %>
        <div class="answer_single panel">
          <div class="author">
            <%= image_tag("default-user.png", :class => "image_author") %>
            <div class="name_author"><%= a.user.name %></div>
          </div>
          <div class="content">
            <p><%= a.description %></p>
            <p class="time"><%= fa_icon "clock-o" %> <%= a.created_at.pretty %></p>
            <div class="comments_to_answer">
              <h4><%= a.comments.count %> Comments for this answer</h4>
              <% a.comments.each do |c| %>
                <div class="comment">
                  <div class="author_name"><%= c.user.name %></div>
                  <div class="comment_text"><%= c.description %></div>
                </div>
              <% end %>
            </div>
            <% if user_signed_in? %>

              <a href="#" class="link" id="add_comment">Add a comment</a>
              <div class="form_comment">
                <% if @errors %>
                <div class="alert alert-danger" role="alert">
                  <ul>
                    <% @errors.each do |error| %>
                    <li><%= error %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>
                <%= form_for [a, a.comments.new] do |f| %>
                  <div class="form-group">
                    <%= f.label 'Comment' %>
                    <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Write your comment here...' %>
                  </div>
                  <div class="form-group">
                    <%= f.submit "Add Comment", class: 'btn btn-custom' %>
                  </div>
                <% end %>
              </div>

          <% end %>
          </div>
          <% if user_signed_in? %>
            <div class="votes">
              <ul>
                <li>
                  <% @vote_allow_answer = a.votes.where(user_id: current_user.id).size > 0 %>
                  <% if @vote_allow_answer %>
                    <span class="up-vote disabled"><%= fa_icon "thumbs-o-up" %></span>
                  <% else %>
                    <%= form_for [a, a.votes.new] do |f| %>
                      <%= f.button fa_icon "thumbs-o-up", class: 'up-vote' %>
                    <% end %>
                  <% end %>
                </li>
                <li><span class="votes-total"><%= a.votes.count %></span></li>
                <li>
                  <% unless @vote_allow_answer %>
                    <span class="down-vote disabled"><%= fa_icon "thumbs-o-down" %></span>
                  <% else %>
                    <%= link_to answer_vote_path(a), method: :delete do %>
                      <%= fa_icon "thumbs-o-down", class: 'down-vote' %>
                    <% end %>
                  <% end %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="your_answer">
        <h3>Your answer</h3>
        <div class="form_answer panel">
          <% if @errors %>
          <div class="alert alert-danger" role="alert">
            <ul>
              <% @errors.each do |error| %>
              <li><%= error %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <%= form_for [@question, @question.answers.new] do |f| %>
            <div class="form-group">
              <%= f.label 'Answer' %>
              <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Write your answer here...' %>
            </div>
            <div class="form-group">
              <%= f.submit "Add Comment", class: 'btn btn-custom' %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-4"></div>
</div>